[project]
name = "image-edit-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "pillow>=11.3.0",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.39.0",
]

[project.scripts]
image-edit-server = "image_edit_server:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
